// Example API Response Structures After Permission Entity Migration

/**
 * Sign In Response
 * POST /api/auth/sign-in
 */
export const signInResponse = {
  success: true,
  accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  sessionId: "550e8400-e29b-41d4-a716-446655440000",
  tokenType: "Bearer",
  expiresIn: "30m",
  expiresAt: "2025-10-20T12:30:00.000Z",
  user: {
    id: "6741150c-f7a0-48ad-94b0-db8480179956",
    email: "admin@example.com",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    role: {
      id: "1",
      name: "Admin",
      description: "Administrator with full access",
      createdBy: "system",
      createdAt: "2025-10-01T00:00:00.000Z",
      updatedAt: "2025-10-20T00:00:00.000Z",
      isActive: true,
      permissions: [
        {
          id: "1",
          permission: "USER_MANAGEMENT",
          name: "User Management",
          canView: true,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
          canSetPermission: true,
          canImport: true,
          canExport: true,
          canSubmit: false,
          canCancel: false,
          canApprove: false,
          canViewSalary: false,
          canEditSalary: false,
          canReject: false,
          canReport: true,
          canAssign: false,
          canViewPartial: false,
          canViewBenefit: false,
          canViewBelongTo: false,
          canViewOwner: false,
          canPermanentlyDelete: true,
          createdBy: "system",
          updatedBy: null,
          deletedBy: null,
          createdAt: "2025-10-01T00:00:00.000Z",
          updatedAt: "2025-10-20T00:00:00.000Z",
          deletedAt: null,
        },
        {
          id: "2",
          permission: "ROLE_MANAGEMENT",
          name: "Role Management",
          canView: true,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: true,
          canSetPermission: true,
          canImport: false,
          canExport: false,
          canSubmit: false,
          canCancel: false,
          canApprove: false,
          canViewSalary: false,
          canEditSalary: false,
          canReject: false,
          canReport: false,
          canAssign: false,
          canViewPartial: false,
          canViewBenefit: false,
          canViewBelongTo: false,
          canViewOwner: false,
          canPermanentlyDelete: false,
          createdBy: "system",
          updatedBy: null,
          deletedBy: null,
          createdAt: "2025-10-01T00:00:00.000Z",
          updatedAt: "2025-10-20T00:00:00.000Z",
          deletedAt: null,
        },
        {
          id: "3",
          permission: "EMPLOYEE_MANAGEMENT",
          name: "Employee Management",
          canView: true,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
          canSetPermission: false,
          canImport: true,
          canExport: true,
          canSubmit: false,
          canCancel: false,
          canApprove: true,
          canViewSalary: true,
          canEditSalary: true,
          canReject: true,
          canReport: true,
          canAssign: true,
          canViewPartial: true,
          canViewBenefit: true,
          canViewBelongTo: true,
          canViewOwner: true,
          canPermanentlyDelete: false,
          createdBy: "system",
          updatedBy: null,
          deletedBy: null,
          createdAt: "2025-10-01T00:00:00.000Z",
          updatedAt: "2025-10-20T00:00:00.000Z",
          deletedAt: null,
        },
      ],
    },
    isActive: true,
    isEmailVerified: true,
    lastLogin: "2025-10-20T11:00:00.000Z",
    unreadNotifications: 5,
  },
  loginTime: "2025-10-20T12:00:00.000Z",
  message: "Sign in successful",
};

/**
 * Set New Password Response
 * POST /api/auth/set-new-password
 */
export const setNewPasswordResponse = {
  success: true,
  accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
  sessionId: "550e8400-e29b-41d4-a716-446655440000",
  tokenType: "Bearer",
  expiresIn: "30m",
  expiresAt: "2025-10-20T12:30:00.000Z",
  user: {
    id: "6741150c-f7a0-48ad-94b0-db8480179956",
    email: "user@example.com",
    firstName: "Jane",
    lastName: "Smith",
    fullName: "Jane Smith",
    role: {
      id: "2",
      name: "Manager",
      description: "Manager with limited access",
      createdBy: "admin",
      createdAt: "2025-10-01T00:00:00.000Z",
      updatedAt: "2025-10-15T00:00:00.000Z",
      isActive: true,
      permissions: [
        {
          id: "3",
          permission: "EMPLOYEE_MANAGEMENT",
          name: "Employee Management",
          canView: true,
          canCreate: false,
          canRead: true,
          canUpdate: true,
          canDelete: false,
          canSetPermission: false,
          canImport: false,
          canExport: true,
          canSubmit: false,
          canCancel: false,
          canApprove: true,
          canViewSalary: false,
          canEditSalary: false,
          canReject: false,
          canReport: true,
          canAssign: true,
          canViewPartial: true,
          canViewBenefit: false,
          canViewBelongTo: true,
          canViewOwner: false,
          canPermanentlyDelete: false,
          createdBy: "admin",
          updatedBy: null,
          deletedBy: null,
          createdAt: "2025-10-01T00:00:00.000Z",
          updatedAt: "2025-10-15T00:00:00.000Z",
          deletedAt: null,
        },
        {
          id: "10",
          permission: "PROJECT_MANAGEMENT",
          name: "Project Management",
          canView: true,
          canCreate: true,
          canRead: true,
          canUpdate: true,
          canDelete: false,
          canSetPermission: false,
          canImport: false,
          canExport: true,
          canSubmit: true,
          canCancel: true,
          canApprove: true,
          canViewSalary: false,
          canEditSalary: false,
          canReject: true,
          canReport: true,
          canAssign: true,
          canViewPartial: true,
          canViewBenefit: false,
          canViewBelongTo: true,
          canViewOwner: true,
          canPermanentlyDelete: false,
          createdBy: "admin",
          updatedBy: null,
          deletedBy: null,
          createdAt: "2025-10-01T00:00:00.000Z",
          updatedAt: "2025-10-15T00:00:00.000Z",
          deletedAt: null,
        },
      ],
    },
    isActive: true,
    isEmailVerified: true,
    lastLogin: "2025-10-20T12:00:00.000Z",
    unreadNotifications: 0,
  },
  loginTime: "2025-10-20T12:00:00.000Z",
  message: "Password updated successfully and user signed in",
};

/**
 * Key Differences from Previous JSONB Structure:
 *
 * 1. permissions is now an ARRAY instead of an object
 * 2. Each permission has ALL fields (id, createdBy, timestamps, etc.)
 * 3. permissions[] matches exactly the Permission type in role.types.ts
 * 4. Better type safety - no more Record<string, any>
 * 5. Proper audit trail with createdBy, updatedBy, deletedBy
 * 6. Each permission is a separate database record
 * 7. Role has createdBy field now
 * 8. Role has updatedAt field (in addition to createdAt)
 */
