-- Insert Sample Departments
-- This script creates departments with hierarchical structure

INSERT INTO departments (
    id,
    name,
    description,
    "parentId",
    type,
    code,
    location,
    "isActive",
    "createdAt",
    "updatedAt"
) VALUES
-- Top Level Departments
(
    gen_random_uuid(),
    'Engineering',
    'Software development and engineering',
    NULL,
    'ENGINEERING',
    'ENG',
    'Multiple Locations',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Product',
    'Product management and strategy',
    NULL,
    'PRODUCT',
    'PROD',
    'San Francisco Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Design',
    'User experience and interface design',
    NULL,
    'DESIGN',
    'DES',
    'Los Angeles Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Human Resources',
    'HR and people operations',
    NULL,
    'HUMAN_RESOURCES',
    'HR',
    'Chicago Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Marketing',
    'Marketing and brand management',
    NULL,
    'MARKETING',
    'MKT',
    'Miami Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Sales',
    'Sales and business development',
    NULL,
    'SALES',
    'SALES',
    'Multiple Locations',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Quality Assurance',
    'Software quality assurance and testing',
    NULL,
    'QUALITY_ASSURANCE',
    'QA',
    'Austin Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Data Science',
    'Data analysis and machine learning',
    NULL,
    'DATA_SCIENCE',
    'DS',
    'Boston Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Security',
    'Information security and cybersecurity',
    NULL,
    'SECURITY',
    'SEC',
    'Seattle Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Customer Support',
    'Customer service and support',
    NULL,
    'CUSTOMER_SUPPORT',
    'CS',
    'New York Office',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Business',
    'Business analysis and operations',
    NULL,
    'BUSINESS',
    'BIZ',
    'Atlanta Office',
    true,
    NOW(),
    NOW()
);

-- Verify departments
SELECT 
    name,
    code,
    type,
    location,
    "isActive"
FROM departments
ORDER BY name;

-- Insert Sample Positions
INSERT INTO positions (
    id,
    name,
    description,
    level,
    code,
    "minSalary",
    "maxSalary",
    "salaryCurrency",
    "isActive",
    "createdAt",
    "updatedAt"
) VALUES
-- Engineering Positions
(
    gen_random_uuid(),
    'Software Engineer Intern',
    'Entry-level software engineering position for students',
    'INTERN',
    'SWE-INT',
    40000,
    60000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Junior Software Engineer',
    'Junior software development position',
    'JUNIOR',
    'SWE-JR',
    70000,
    95000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Software Engineer',
    'Mid-level software development position',
    'INTERMEDIATE',
    'SWE-MID',
    95000,
    125000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior Software Engineer',
    'Senior software development position',
    'SENIOR',
    'SWE-SR',
    120000,
    170000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Staff Software Engineer',
    'Staff-level technical position',
    'LEAD',
    'SWE-STAFF',
    160000,
    220000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Principal Software Engineer',
    'Principal-level technical position',
    'PRINCIPAL',
    'SWE-PRIN',
    200000,
    280000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Engineering Manager',
    'Engineering team management position',
    'MANAGER',
    'ENG-MGR',
    140000,
    190000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior Engineering Manager',
    'Senior engineering management position',
    'SENIOR_MANAGER',
    'ENG-SMGR',
    180000,
    240000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Director of Engineering',
    'Engineering director position',
    'DIRECTOR',
    'ENG-DIR',
    220000,
    300000,
    'USD',
    true,
    NOW(),
    NOW()
),
-- Product Positions
(
    gen_random_uuid(),
    'Associate Product Manager',
    'Entry-level product management',
    'JUNIOR',
    'PM-ASSOC',
    85000,
    110000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Product Manager',
    'Product management position',
    'INTERMEDIATE',
    'PM-MID',
    110000,
    145000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior Product Manager',
    'Senior product management position',
    'SENIOR',
    'PM-SR',
    140000,
    185000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Director of Product',
    'Product director position',
    'DIRECTOR',
    'PROD-DIR',
    200000,
    270000,
    'USD',
    true,
    NOW(),
    NOW()
),
-- Design Positions
(
    gen_random_uuid(),
    'Junior Designer',
    'Entry-level design position',
    'JUNIOR',
    'DES-JR',
    65000,
    85000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UX/UI Designer',
    'Mid-level design position',
    'INTERMEDIATE',
    'DES-MID',
    85000,
    115000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior UX/UI Designer',
    'Senior design position',
    'SENIOR',
    'DES-SR',
    110000,
    150000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Lead Designer',
    'Design team lead position',
    'LEAD',
    'DES-LEAD',
    130000,
    175000,
    'USD',
    true,
    NOW(),
    NOW()
),
-- QA Positions
(
    gen_random_uuid(),
    'QA Engineer',
    'Quality assurance engineer',
    'INTERMEDIATE',
    'QA-MID',
    80000,
    110000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior QA Engineer',
    'Senior quality assurance engineer',
    'SENIOR',
    'QA-SR',
    105000,
    140000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'QA Lead',
    'Quality assurance team lead',
    'LEAD',
    'QA-LEAD',
    120000,
    160000,
    'USD',
    true,
    NOW(),
    NOW()
),
-- Data Science Positions
(
    gen_random_uuid(),
    'Data Analyst',
    'Data analysis position',
    'INTERMEDIATE',
    'DA-MID',
    75000,
    105000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Data Scientist',
    'Data science position',
    'SENIOR',
    'DS-SR',
    120000,
    165000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Senior Data Scientist',
    'Senior data science position',
    'SENIOR',
    'DS-SR2',
    150000,
    200000,
    'USD',
    true,
    NOW(),
    NOW()
),
-- Other Positions
(
    gen_random_uuid(),
    'DevOps Engineer',
    'DevOps engineering position',
    'SENIOR',
    'DEVOPS-SR',
    120000,
    165000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Security Engineer',
    'Information security position',
    'SENIOR',
    'SEC-SR',
    130000,
    180000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'HR Manager',
    'Human resources management',
    'MANAGER',
    'HR-MGR',
    90000,
    125000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Marketing Manager',
    'Marketing management position',
    'MANAGER',
    'MKT-MGR',
    85000,
    120000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Sales Manager',
    'Sales management position',
    'MANAGER',
    'SALES-MGR',
    90000,
    130000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Business Analyst',
    'Business analysis position',
    'INTERMEDIATE',
    'BA-MID',
    80000,
    110000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Customer Support Lead',
    'Customer support team lead',
    'LEAD',
    'CS-LEAD',
    65000,
    90000,
    'USD',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Content Writer',
    'Content writing position',
    'INTERMEDIATE',
    'CONT-WR',
    50000,
    75000,
    'USD',
    true,
    NOW(),
    NOW()
);

-- Verify positions
SELECT 
    name,
    code,
    level,
    "minSalary",
    "maxSalary",
    "salaryCurrency"
FROM positions
ORDER BY "minSalary" DESC;
